// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-p71XXsahlFMAGsZyP2Rgo9x-Oi1Xy7I',
    appId: '1:989501248660:android:da06bd42379e9fbe805081',
    messagingSenderId: '989501248660',
    projectId: 'ma3ak-6992f',
    databaseURL: 'https://ma3ak-6992f-default-rtdb.firebaseio.com',
    storageBucket: 'ma3ak-6992f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmGubm7bMM-rSFi712ZGRGXGikVubmfPk',
    appId: '1:989501248660:ios:a68f592b1c35e561805081',
    messagingSenderId: '989501248660',
    projectId: 'ma3ak-6992f',
    databaseURL: 'https://ma3ak-6992f-default-rtdb.firebaseio.com',
    storageBucket: 'ma3ak-6992f.firebasestorage.app',
    iosBundleId: 'com.evyx.maak',
  );
}
