// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2LrCe11GeFZC2d1fTjok8yTAX14S5ByM',
    appId: '1:514044255637:android:627e19a22f59525836ea9c',
    messagingSenderId: '514044255637',
    projectId: 'captain-masr-4acb2',
    databaseURL: 'https://captain-masr-4acb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'captain-masr-4acb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApPb9lRZL8DktrTu6Wekh17K_RFsSar18',
    appId: '1:514044255637:ios:aafe0e6acaf7a35e36ea9c',
    messagingSenderId: '514044255637',
    projectId: 'captain-masr-4acb2',
    databaseURL: 'https://captain-masr-4acb2-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'captain-masr-4acb2.firebasestorage.app',
    iosBundleId: 'com.evyx.captainMasrRider',
  );
}
